### ISSUE TITLE
Can't get NBT in on steer event.

### ISSUE THREAD

**Issue by IveyFake** [TheLimeGlass/Skacket#113]
```
on steering vehicle:
	broadcast "steering"
	broadcast "%nbt of player%" #this doesn't broadcast
```

Skacket v1.0.13, Skript v2.7.0-beta3, skript-reflect v2.4-dev1, ProtocolLib v5.1.0, SkBee v2.15.1

git-Paper-111 1.20.1-R0.1-SNAPSHOT

**Comment by TheLimeGlass** [comment]
Skacket does not have NBT

**Comment by IveyFake** [comment]
Skbee does but it doesn't work when using this Skacket event.

**Comment by IveyFake** [comment]
heres the console error I recieve.
`[00:32:12 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:312)
[00:32:12 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:329)
[00:32:12 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.effects.EffBroadcast.lambda$execute$2(EffBroadcast.java:102)
[00:32:12 ERROR]: #!#!     at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[00:32:12 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:102)
[00:32:12 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[00:32:12 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[00:32:12 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[00:32:12 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[00:32:12 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
[00:32:12 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:50)
[00:32:12 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:63)
[00:32:12 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[00:32:12 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:32:12 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[00:32:12 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[00:32:12 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[00:32:12 ERROR]: #!#!     at Skacket-1.0.13.jar//me.limeglass.skacket.listeners.PacketListeners$2.onPacketReceiving(PacketListeners.java:84)
[00:32:12 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:122)
[00:32:12 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:75)
[00:32:12 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:555)
[00:32:12 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:519)
[00:32:12 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:118)
[00:32:12 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:500)
[00:32:12 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:12 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:32:12 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:12 ERROR]: #!#!     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:12 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:32:12 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:12 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:32:12 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:12 ERROR]: #!#!     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:12 ERROR]: #!#!     at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:12 ERROR]: #!#!     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[00:32:12 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:12 ERROR]: #!#!     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[00:32:12 ERROR]: #!#!     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[00:32:12 ERROR]: #!#!     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[00:32:12 ERROR]: #!#!     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[00:32:12 ERROR]: #!#!     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:32:12 ERROR]: #!#!     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:32:12 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[00:32:12 ERROR]: #!#! 
[00:32:12 ERROR]: #!#! Version Information:
[00:32:12 ERROR]: #!#!   Skript: 2.7.0-beta3 (latest)
[00:32:12 ERROR]: #!#!     Flavor: skriptlang-github
[00:32:12 ERROR]: #!#!     Date: 03:18:03.366646700
[00:32:12 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[00:32:12 ERROR]: #!#!   Minecraft: 1.20.1
[00:32:12 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[00:32:12 ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic
[00:32:12 ERROR]: #!#! 
[00:32:12 ERROR]: #!#! Server platform: Paper
[00:32:12 ERROR]: #!#! 
[00:32:12 ERROR]: #!#! Current node: null
[00:32:12 ERROR]: #!#! Current item: broadcast nbt compound from the player
[00:32:12 ERROR]: #!#! Current trigger: steering vehicle (on vehicle steer) (Game.sk, line 334)
[00:32:12 ERROR]: #!#! 
[00:32:12 ERROR]: #!#! Thread: Netty Epoll Server IO #1
[00:32:12 ERROR]: #!#! 
[00:32:12 ERROR]: #!#! Language: english
[00:32:12 ERROR]: #!#! Link parse mode: DISABLED
[00:32:12 ERROR]: #!#! 
[00:32:12 ERROR]: #!#! End of Error.
[00:32:12 ERROR]: #!#! 
[00:32:39 INFO]: Reta issued server command: /sk reload Game
[00:32:48 INFO]: steering
[00:32:48 ERROR]: #!#! 
[00:32:48 ERROR]: #!#! [Skript] Severe Error:
[00:32:48 ERROR]: #!#! 
[00:32:48 ERROR]: #!#! Something went horribly wrong with Skript.
[00:32:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:32:48 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:32:48 ERROR]: #!#! Following plugins are probably related to this error in some way:
[00:32:48 ERROR]: #!#! Skacket 
[00:32:48 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:32:48 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:32:48 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:32:48 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:32:48 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:32:48 ERROR]: #!#! 
[00:32:48 ERROR]: #!#! Stack trace:
[00:32:48 ERROR]: #!#! java.lang.IllegalArgumentException: message cannot be null
[00:32:48 ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[00:32:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:317)
[00:32:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:312)
[00:32:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:329)
[00:32:48 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.effects.EffBroadcast.lambda$execute$2(EffBroadcast.java:102)
[00:32:48 ERROR]: #!#!     at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[00:32:48 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:102)
[00:32:48 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[00:32:48 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[00:32:48 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[00:32:48 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[00:32:48 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
[00:32:48 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:50)
[00:32:48 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:63)
[00:32:48 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[00:32:48 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:32:48 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[00:32:48 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[00:32:48 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[00:32:48 ERROR]: #!#!     at Skacket-1.0.13.jar//me.limeglass.skacket.listeners.PacketListeners$2.onPacketReceiving(PacketListeners.java:84)
[00:32:48 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:122)
[00:32:48 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:75)
[00:32:48 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:555)
[00:32:48 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:519)
[00:32:48 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:118)
[00:32:48 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:500)
[00:32:48 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:48 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:32:48 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:48 ERROR]: #!#!     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:48 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:32:48 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:48 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:32:48 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[00:32:48 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[00:32:48 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:48 ERROR]: #!#!     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:48 ERROR]: #!#!     at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:32:48 ERROR]: #!#!     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[00:32:48 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:32:48 ERROR]: #!#!     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[00:32:48 ERROR]: #!#!     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[00:32:48 ERROR]: #!#!     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[00:32:48 ERROR]: #!#!     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[00:32:48 ERROR]: #!#!     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:32:48 ERROR]: #!#!     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:32:48 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[00:32:48 ERROR]: #!#! 
[00:32:48 ERROR]: #!#! Version Information:
[00:32:48 ERROR]: #!#!   Skript: 2.7.0-beta3 (latest)
[00:32:48 ERROR]: #!#!     Flavor: skriptlang-github
[00:32:48 ERROR]: #!#!     Date: 03:18:03.366646700
[00:32:48 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[00:32:48 ERROR]: #!#!   Minecraft: 1.20.1
[00:32:48 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[00:32:48 ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic
[00:32:48 ERROR]: #!#! 
[00:32:48 ERROR]: #!#! Server platform: Paper
[00:32:48 ERROR]: #!#! 
[00:32:48 ERROR]: #!#! Current node: null
[00:32:48 ERROR]: #!#! Current item: broadcast nbt compound from the player
[00:32:48 ERROR]: #!#! Current trigger: steering vehicle (on vehicle steer) (Game.sk, line 334)
[00:32:48 ERROR]: #!#! 
[00:32:48 ERROR]: #!#! Thread: Netty Epoll Server IO #1
[00:32:48 ERROR]: #!#! 
[00:32:48 ERROR]: #!#! Language: english
[00:32:48 ERROR]: #!#! Link parse mode: DISABLED
[00:32:48 ERROR]: #!#! 
[00:32:48 ERROR]: #!#! End of Error.
[00:32:48 ERROR]: #!#! `

**Comment by IveyFake** [comment]
> Skacket does not have NBT

This is still a problem caused by skacket though? A conflict between plugins?
