### ISSUE TITLE
Anvil gui not working.

### ISSUE THREAD

**Issue by ffddf111** [TheLimeGlass/Skacket#133]
[09:46:42 ERROR]: Could not pass event InventoryClickEvent to Skript v2.8.0
java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
at net.wesjd.anvilgui.AnvilGUI$Builder.(AnvilGUI.java:385) ~[Skacket-1.1.0.jar:?]
at me.limeglass.skacket.elements.sections.SecOpenAnvil.walk(SecOpenAnvil.java:98) ~[Skacket-1.1.0.jar:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[Skript.jar:?]
at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript.jar:?]
at ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155) ~[Skript.jar:?]
at ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166) ~[Skript.jar:?]
at ch.njol.skript.util.Task.callSync(Task.java:164) ~[Skript.jar:?]
at ch.njol.skript.util.Task.callSync(Task.java:148) ~[Skript.jar:?]
at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164) ~[Skript.jar:?]
at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[Skript.jar:?]
at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66) ~[Skript.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2127]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2127]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2127]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3193) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1486) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1463) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1386) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1364) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1254) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2127]
at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: AnvilGUI does not support server version "1_20_R3" [in thread "Server thread"]
at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:32) ~[Skacket-1.1.0.jar:?]
at net.wesjd.anvilgui.AnvilGUI.(AnvilGUI.java:43) ~[Skacket-1.1.0.jar:?]
... 33 more
[09:46:42 ERROR]: Could not pass event InventoryClickEvent to Skript v2.8.0
java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
at net.wesjd.anvilgui.AnvilGUI$Builder.(AnvilGUI.java:385) ~[Skacket-1.1.0.jar:?]
at me.limeglass.skacket.elements.sections.SecOpenAnvil.walk(SecOpenAnvil.java:98) ~[Skacket-1.1.0.jar:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[Skript.jar:?]
at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript.jar:?]
at ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155) ~[Skript.jar:?]
at ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166) ~[Skript.jar:?]
at ch.njol.skript.util.Task.callSync(Task.java:164) ~[Skript.jar:?]
at ch.njol.skript.util.Task.callSync(Task.java:148) ~[Skript.jar:?]
at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164) ~[Skript.jar:?]
at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[Skript.jar:?]
at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66) ~[Skript.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2127]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2127]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2127]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3193) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1486) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1463) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1386) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1364) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1254) ~[purpur-1.20.4.jar:git-Purpur-2127]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2127]
at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: AnvilGUI does not support server version "1_20_R3" [in thread "Server thread"]
at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:32) ~[Skacket-1.1.0.jar:?]
at net.wesjd.anvilgui.AnvilGUI.(AnvilGUI.java:43) ~[Skacket-1.1.0.jar:?]
... 33 more

**Comment by TheLimeGlass** [comment]
Updated in 1.1.1
