### ISSUE TITLE
Skacket Console Error

### ISSUE THREAD

**Issue by Netherpwn** [TheLimeGlass/Skacket#14]
`
[03:04:00 ERROR]: Error occurred while enabling Skacket v1.0.5 (Is it up to date?)
java.lang.NoSuchMethodError: com.comphenix.protocol.injector.packet.PacketRegistry.toPacketTypes(Ljava/util/Set;)Ljava/util/Set;
at com.comphenix.protocol.events.ListeningWhitelist.<init>(ListeningWhitelist.java:96) ~[?:?]
at com.comphenix.protocol.events.ListeningWhitelist.<clinit>(ListeningWhitelist.java:41) ~[?:?]
at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:44) ~[?:?]
at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:52) ~[?:?]
at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:104) ~[?:?]
at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:64) ~[?:?]
at me.limeglass.skacket.listeners.PacketListeners$1.<init>(PacketListeners.java:29) ~[?:?]
at me.limeglass.skacket.listeners.PacketListeners.<clinit>(PacketListeners.java:29) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_275]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_275]
at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) ~[?:?]
at me.limeglass.skacket.Skacket.onEnable(Skacket.java:43) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-434]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-434]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-434]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-434]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-434]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.5.jar:git-Paper-434]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-434]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.5.jar:git-Paper-434]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-434]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[03:04:00 INFO]: [Skacket] Disabling Skacket v1.0.5
`
I had this working for like a day and after that it throws this error then disables itself. I also tried to remove all of my plugins except for ProtocolLib, Skript and Skacket but still no luck.

Server Version: Paper 1.16.5 (#434), Although I tried using Paper 1.16.4 (#416) with same results
Skript Version: 2.5.3
Skacket Version: 1.0.5
ProtocolLib:  Version #492 in their Jenkins

**Comment by TheLimeGlass** [comment]
Currently a known issue with ProtocolLib https://github.com/dmulloy2/ProtocolLib/issues/1056

**Comment by TheLimeGlass** [comment]
Try with the latest 4.6.0 version of ProtocolLib

**Comment by TheLimeGlass** [comment]
Still present in 4.6.0 unfortunately

**Comment by TheLimeGlass** [comment]
Fixed in 4.7.0 of ProtocolLib
