### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LordBartosz-tech** [TheLimeGlass/Skacket#26]
I tried to use Skacket to give the fake armor to player but I got an error on the console

Code:
```
command /test:
    Trigger:
        make all players appear to be wearing diamond helmet in slot itemslot.head
```
Server version: Purpur 1.16.1

Console Error:
```
[15:01:54] [Server thread/INFO]: LordBartosz issued server command: /test
[15:01:54] [Server thread/INFO]: LordBartosz [a2ad638d-4a7f-30e9-b536-eec94a25e6fe]: /test
[15:01:54] [Server thread/WARN]: [Skript] No matching field: ClassInfo#head
[15:01:54] [Server thread/ERROR]: #!#! 
[15:01:54] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[15:01:54] [Server thread/ERROR]: #!#! 
[15:01:54] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[15:01:54] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:01:54] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:01:54] [Server thread/ERROR]: #!#! Here is full list of them:
[15:01:54] [Server thread/ERROR]: #!#! skript-reflect v2.2.1 (https://github.com/TPGamesNL/skript-reflect) Skacket v1.0.5 
[15:01:54] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:01:54] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:01:54] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:01:54] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:01:54] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:01:54] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:01:54] [Server thread/ERROR]: #!#! 
[15:01:54] [Server thread/ERROR]: #!#! Stack trace:
[15:01:54] [Server thread/ERROR]: #!#! FieldAccessException: No field with type net.minecraft.server.v1_16_R1.ItemStack exists in class PacketPlayOutEntityEquipment.
[15:01:54] [Server thread/ERROR]: #!#!     at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:363)
[15:01:54] [Server thread/ERROR]: #!#!     at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:343)
[15:01:54] [Server thread/ERROR]: #!#!     at me.limeglass.skacket.wrappers.WrapperPlayServerEntityEquipment.setItem(WrapperPlayServerEntityEquipment.java:90)
[15:01:54] [Server thread/ERROR]: #!#!     at me.limeglass.skacket.elements.effects.EffArmourChange.setArmour(EffArmourChange.java:86)
[15:01:54] [Server thread/ERROR]: #!#!     at me.limeglass.skacket.elements.effects.EffArmourChange.execute(EffArmourChange.java:58)
[15:01:54] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[15:01:54] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[15:01:54] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:01:54] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[15:01:54] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:291)
[15:01:54] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[15:01:54] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:248)
[15:01:54] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[15:01:54] [Server thread/ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[15:01:54] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:01:54] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:01:54] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1968)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1779)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1205)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1198)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1174)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1018)
[15:01:54] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[15:01:54] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[15:01:54] [Server thread/ERROR]: #!#! 
[15:01:54] [Server thread/ERROR]: #!#! Version Information:
[15:01:54] [Server thread/ERROR]: #!#!   Skript: 2.5.3 (latest)
[15:01:54] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[15:01:54] [Server thread/ERROR]: #!#!     Date: 2020-12-11
[15:01:54] [Server thread/ERROR]: #!#!   Bukkit: 1.16.1-R0.1-SNAPSHOT
[15:01:54] [Server thread/ERROR]: #!#!   Minecraft: 1.16.1
[15:01:54] [Server thread/ERROR]: #!#!   Java: 1.8.0_281 (Java HotSpot(TM) 64-Bit Server VM 25.281-b09)
[15:01:54] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:01:54] [Server thread/ERROR]: #!#! 
[15:01:54] [Server thread/ERROR]: #!#! Server platform: Paper
[15:01:54] [Server thread/ERROR]: #!#! 
[15:01:54] [Server thread/ERROR]: #!#! Current node: null
[15:01:54] [Server thread/ERROR]: #!#! Current item: client side armour
[15:01:54] [Server thread/ERROR]: #!#! Current trigger: command /test (simple event) (test.sk, line -1)
[15:01:54] [Server thread/ERROR]: #!#! 
[15:01:54] [Server thread/ERROR]: #!#! Thread: Server thread
[15:01:54] [Server thread/ERROR]: #!#! 
[15:01:54] [Server thread/ERROR]: #!#! Language: english
[15:01:54] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[15:01:54] [Server thread/ERROR]: #!#! 
[15:01:54] [Server thread/ERROR]: #!#! End of Error.
[15:01:54] [Server thread/ERROR]: #!#! 
```

**Comment by TheLimeGlass** [comment]
Will investigate when a working version of ProtocolLib comes out.

**Comment by TheLimeGlass** [comment]
Added 1.16+ support in version 1.0.7 of Skacket.
