### ISSUE TITLE
block break animation not working in 1.16.5, protocollib issue?

### ISSUE THREAD

**Issue by GovindasOM** [TheLimeGlass/Skacket#36]
```
[09:43:41 ERROR]: #!#! Stack trace:
[09:43:41 ERROR]: #!#! FieldAccessException: No field with type java.util.Map exists in class EnumProtocol.
[09:43:41 ERROR]: #!#!     at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216)
[09:43:41 ERROR]: #!#!     at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195)
[09:43:41 ERROR]: #!#!     at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:57)
[09:43:41 ERROR]: #!#!     at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59)
[09:43:41 ERROR]: #!#!     at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:38)
[09:43:41 ERROR]: #!#!     at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
[09:43:41 ERROR]: #!#!     at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
[09:43:41 ERROR]: #!#!     at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:63)
[09:43:41 ERROR]: #!#!     at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:152)
[09:43:41 ERROR]: #!#!     at me.limeglass.skacket.wrappers.WrapperPlayServerBlockBreakAnimation.<init>(WrapperPlayServerBlockBreakAnimation.java:16)
[09:43:41 ERROR]: #!#!     at me.limeglass.skacket.elements.effects.EffBlockBreakAnimation.execute(EffBlockBreakAnimation.java:63)
[09:43:41 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[09:43:41 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[09:43:41 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[09:43:41 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:273)
[09:43:41 ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:207)
[09:43:41 ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:1)
[09:43:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftFuture.run(CraftFuture.java:88)
[09:43:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[09:43:41 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503)
[09:43:41 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449)
[09:43:41 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416)
[09:43:41 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142)
[09:43:41 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[09:43:41 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[09:43:41 ERROR]: #!#! 
[09:43:41 ERROR]: #!#! Version Information:
[09:43:41 ERROR]: #!#!   Skript: 2.5.1
[09:43:41 ERROR]: #!#!     Flavor: skriptlang-github
[09:43:41 ERROR]: #!#!     Date: 2020-10-22
[09:43:41 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[09:43:41 ERROR]: #!#!   Minecraft: 1.16.5
[09:43:41 ERROR]: #!#!   Java: 11.0.10 (OpenJDK 64-Bit Server VM 11.0.10+9)
[09:43:41 ERROR]: #!#!   OS: Linux amd64 5.4.0-66-generic
[09:43:41 ERROR]: #!#! 
[09:43:41 ERROR]: #!#! Server platform: Paper
[09:43:41 ERROR]: #!#! 
[09:43:41 ERROR]: #!#! Current node: null
[09:43:41 ERROR]: #!#! Current item: block break animation
[09:43:41 ERROR]: #!#! 
[09:43:41 ERROR]: #!#! Thread: Server thread
[09:43:41 ERROR]: #!#! 
[09:43:41 ERROR]: #!#! Language: english
[09:43:41 ERROR]: #!#! Link parse mode: LENIENT
[09:43:41 ERROR]: #!#! 
[09:43:41 ERROR]: #!#! End of Error.
[09:43:41 ERROR]: #!#! 
```

**Comment by TheLimeGlass** [comment]
Will investigate when a working version of ProtocolLib comes out.

**Comment by TheLimeGlass** [comment]
Update your protocollib

**Comment by TheLimeGlass** [comment]
Cannot replicate in newer versions
