### ISSUE TITLE
Console error, my skript error after add skacket

### ISSUE THREAD

**Issue by Mightinity** [TheLimeGlass/Skacket#39]
[22:56:00 INFO]: [Skacket] Enabling Skacket v1.0.5
[22:56:00 ERROR]: #!#! 
[22:56:00 ERROR]: #!#! [Skript] Severe Error:
[22:56:00 ERROR]: #!#! Skacket's class me.limeglass.skacket.listeners.PacketListeners generated an exception while loading
[22:56:00 ERROR]: #!#! 
[22:56:00 ERROR]: #!#! Something went horribly wrong with Skript.
[22:56:00 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:56:00 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:56:00 ERROR]: #!#! Following plugins are probably related to this error in some way:
[22:56:00 ERROR]: #!#! Skacket 
[22:56:00 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:56:00 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:56:00 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:56:00 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:56:00 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:56:00 ERROR]: #!#! 
[22:56:00 ERROR]: #!#! Stack trace:
[22:56:00 ERROR]: #!#! java.lang.NullPointerException
[22:56:00 ERROR]: #!#!     at me.limeglass.skacket.listeners.PacketListeners.<clinit>(PacketListeners.java:29)
[22:56:00 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[22:56:00 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:398)
[22:56:00 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107)
[22:56:00 ERROR]: #!#!     at me.limeglass.skacket.Skacket.onEnable(Skacket.java:43)
[22:56:00 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[22:56:00 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[22:56:00 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[22:56:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[22:56:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[22:56:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[22:56:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[22:56:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[22:56:00 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[22:56:00 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[22:56:00 ERROR]: #!#! 
[22:56:00 ERROR]: #!#! Version Information:
[22:56:00 ERROR]: #!#!   Skript: 2.5.3 (latest)
[22:56:00 ERROR]: #!#!     Flavor: skriptlang-github
[22:56:00 ERROR]: #!#!     Date: 2020-12-11
[22:56:00 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[22:56:00 ERROR]: #!#!   Minecraft: 1.16.5
[22:56:00 ERROR]: #!#!   Java: 11.0.10 (OpenJDK 64-Bit Server VM 11.0.10+9)
[22:56:00 ERROR]: #!#!   OS: Linux amd64 5.4.0-1045-aws
[22:56:00 ERROR]: #!#! 
[22:56:00 ERROR]: #!#! Server platform: Paper
[22:56:00 ERROR]: #!#! 
[22:56:00 ERROR]: #!#! Current node: null
[22:56:00 ERROR]: #!#! Current item: null
[22:56:00 ERROR]: #!#! 
[22:56:00 ERROR]: #!#! Thread: Server thread
[22:56:00 ERROR]: #!#! 
[22:56:00 ERROR]: #!#! Language: english
[22:56:00 ERROR]: #!#! Link parse mode: DISABLED
[22:56:00 ERROR]: #!#! 
[22:56:00 ERROR]: #!#! End of Error.
[22:56:00 ERROR]: #!#! 
[22:56:00 INFO]: [Skacket] Skacket has been enabled!

**Comment by TheLimeGlass** [comment]
Duplicate #40
