### ISSUE TITLE
Region event problem on Skript 2.6.1

### ISSUE THREAD

**Issue by OverBrave** [TheLimeGlass/Skacket#62]
### Skript/Server Version

```
[13:41:37 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:41:37 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[13:41:37 INFO]: [Skript] Server Version: git-Pufferfish-39 (MC: 1.18.1)
[13:41:37 INFO]: [Skript] Skript Version: 2.6.1-nightly-5fa019e
[13:41:37 INFO]: [Skript] Installed Skript Addons:
[13:41:37 INFO]: [Skript]  - skript-placeholders v1.5.1 (https://github.com/APickledWalrus/skript-placeholders)
[13:41:37 INFO]: [Skript]  - Skacket v1.0.7
[13:41:37 INFO]: [Skript]  - DiSky v2.3 (https://disky.itsthesky.info/)
[13:41:37 INFO]: [Skript]  - skript-yaml v1.4
[13:41:37 INFO]: [Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[13:41:37 INFO]: [Skript]  - skript-db v1.3.3
[13:41:37 INFO]: [Skript]  - SharpSK v1.6.13
[13:41:37 INFO]: [Skript] Installed dependencies:
[13:41:37 INFO]: [Skript]  - Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[13:41:37 INFO]: [Skript]  - WorldGuard v7.0.6+1cff55f
```

### Bug Description

```
on region enter:
    message "Entering %region%."
```

She stated that the problem occurred because it has not been updated yet by the Skacket developer.

Sometimes sending this error on console:
```
[13:21:45] [Server thread/ERROR]: #!#! Stack trace:
[13:21:45] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for sound
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:71)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[13:21:45] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1096)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1067)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:739)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1060)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[13:21:45] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[13:21:45] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[13:21:45] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2080)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1415)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1393)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1386)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1364)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1270)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
[13:21:45] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected Behavior

Region entries/exites should work.

### Steps to Reproduce

```
on region enter:
    message "Entering %region%."
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

https://github.com/SkriptLang/Skript/issues/4568

**Comment by TheLimeGlass** [comment]
Fixed in 1.0.8 which is released here https://github.com/TheLimeGlass/Skacket/releases/tag/1.0.8

Thanks for the report!

**Comment by OverBrave** [comment]
> Fixed in 1.0.8 which is released here https://github.com/TheLimeGlass/Skacket/releases/tag/1.0.8
> 
> Thanks for the report!

```
[14:07:26] [Server thread/ERROR]: #!#! 
[14:07:26] [Server thread/ERROR]: #!#! Stack trace:
[14:07:26] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for sound
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:71)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[14:07:26] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1096)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1067)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:739)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[14:07:26] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[14:07:26] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:07:26] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:07:26] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1213)
[14:07:26] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
[14:07:26] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[14:07:26] [Server thread/ERROR]: #!#! 
[14:07:26] [Server thread/ERROR]: #!#! Version Information:
[14:07:26] [Server thread/ERROR]: #!#!   Skript: 2.6.1-nightly-2d2f383
[14:07:26] [Server thread/ERROR]: #!#!     Flavor: skriptlang-nightly
[14:07:26] [Server thread/ERROR]: #!#!     Date: 09:54:24.829354045
[14:07:26] [Server thread/ERROR]: #!#!   Bukkit: 1.18.1-R0.1-SNAPSHOT
[14:07:26] [Server thread/ERROR]: #!#!   Minecraft: 1.18.1
[14:07:26] [Server thread/ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12-LTS)
[14:07:26] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.10.0-1160.49.1.el7.x86_64
[14:07:26] [Server thread/ERROR]: #!#! 
[14:07:26] [Server thread/ERROR]: #!#! Server platform: Paper
[14:07:26] [Server thread/ERROR]: #!#! 
[14:07:26] [Server thread/ERROR]: #!#! Current node: on leaving of region "spawn": (scgiris.sk, line 41)
[14:07:26] [Server thread/ERROR]: #!#! Current item: null
```
Problem still persist.

**Comment by TheLimeGlass** [comment]
Ok, can you install this Skript version https://github.com/SkriptLang/Skript/pull/4546
Click the checks tab, then artifacts. Then get it to error again and post the error. This version of Skript is built on 2.6.1 and it will show me more information about which syntax is erroring.

**Comment by OverBrave** [comment]
> Ok, can you install this Skript version [SkriptLang/Skript#4546](https://github.com/SkriptLang/Skript/pull/4546) Click the checks tab, then artifacts. Then get it to error again and post the error. This version of Skript is built on 2.6.1 and it will show me more information about which syntax is erroring. Could be another addon which I don't know of that has `sound` classinfo.

After deleting the Skacket plugin, the event continues to run. I downloaded the version you said and the result is:
````
[15:03:22] [Server thread/ERROR]: #!#! Stack trace:
[15:03:22] [Server thread/ERROR]: #!#! ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: [named] sound [%sounds%] [(trigger|play)]]
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:54)
[15:03:22] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1096)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1067)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:739)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[15:03:22] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:03:22] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:03:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1213)
[15:03:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
[15:03:22] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[15:03:22] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for sound
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:77)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[15:03:22] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1096)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1067)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:739)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[15:03:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[15:03:22] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:03:22] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:03:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1213)
[15:03:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
[15:03:22] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by OverBrave** [comment]
Ok, the problem is fixed in the remastered version. Thank you!
