### ISSUE TITLE
Skript-gui error with Skacket

### ISSUE THREAD

**Issue by Deichor** [TheLimeGlass/Skacket#63]
`[13:28:50 ERROR]: Could not pass event InventoryClickEvent to skript-gui v1.3-beta1
java.lang.ExceptionInInitializerError: null
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[Skacket-1.0.8.jar:?]
        at me.limeglass.skacket.elements.sections.SecOpenAnvil.walk(SecOpenAnvil.java:116) ~[Skacket-1.0.8.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[Skript2.6.1.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript2.6.1.jar:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85) ~[Skript2.6.1.jar:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:129) ~[Skript2.6.1.jar:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:288) ~[Skript2.6.1.jar:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[Skript2.6.1.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[Skript2.6.1.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[Skript2.6.1.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[Skript2.6.1.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript2.6.1.jar:?]
        at io.github.apickledwalrus.skriptgui.elements.sections.SecMakeGUI.lambda$walk$0(SecMakeGUI.java:115) ~[skript-gui-1.3-beta1.jar:?]
        at io.github.apickledwalrus.skriptgui.gui.GUI$1.onClick(GUI.java:45) ~[skript-gui-1.3-beta1.jar:?]
        at io.github.apickledwalrus.skriptgui.gui.events.GUIEvents.onInventoryClick(GUIEvents.java:123) ~[skript-gui-1.3-beta1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor9.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-182]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2842) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-182]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: AnvilGUI does not support server version "1_18_R1"
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:26) ~[Skacket-1.0.8.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[Skacket-1.0.8.jar:?]
        ... 37 more
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.version.Wrapper1_18_R1
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:22) ~[Skacket-1.0.8.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[Skacket-1.0.8.jar:?]
        ... 37 more`

**Comment by TheLimeGlass** [comment]
Fixed in 1.0.9
