### ISSUE TITLE
Issue with client side armor

### ISSUE THREAD

**Issue by ImNotStable** [TheLimeGlass/Skacket#68]
`[08:32:19 ERROR]: #!#!
[08:32:19 ERROR]: #!#! [Skript] Severe Error:
[08:32:19 ERROR]: #!#!
[08:32:19 ERROR]: #!#! Something went horribly wrong with Skript.
[08:32:19 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[08:32:19 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[08:32:19 ERROR]: #!#! Here is full list of them:
[08:32:19 ERROR]: #!#! SkJade v1.4 (https://www.github.com/Ankoki-Dev/SkJade) SkBee v1.15.1 (https://github.com/ShaneBeee/SkBee) skUtilities v0.9.2 (https://tim740.github.io/) Skacket v1.0.8 SkQuery v4.1.6 skript-logs v0.1.3 (https://github.com/Blueyescat/skript-logs)
[08:32:19 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[08:32:19 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[08:32:19 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[08:32:19 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[08:32:19 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[08:32:19 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[08:32:19 ERROR]: #!#!
[08:32:19 ERROR]: #!#! Stack trace:
[08:32:19 ERROR]: #!#! java.lang.ClassCastException: class ch.njol.skript.aliases.ItemType cannot be cast to class org.bukkit.inventory.ItemStack (ch.njol.skript.aliases.ItemType is in unnamed module of loader 'Skript-2.6.1.jar' @30e7c3cd; org.bukkit.inventory.ItemStack is in unnamed module of loader java.net.URLClassLoader @3b764bce)
[08:32:19 ERROR]: #!#!     at Skacket-1.0.8.jar//me.limeglass.skacket.elements.effects.EffArmourChange.lambda$execute$0(EffArmourChange.java:71)
[08:32:19 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[08:32:19 ERROR]: #!#!     at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
[08:32:19 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[08:32:19 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[08:32:19 ERROR]: #!#!     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[08:32:19 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[08:32:19 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[08:32:19 ERROR]: #!#!     at Skacket-1.0.8.jar//me.limeglass.skacket.elements.effects.EffArmourChange.execute(EffArmourChange.java:72)
[08:32:19 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.lang.Effect.run(Effect.java:51)
[08:32:19 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[08:32:19 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[08:32:19 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[08:32:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[08:32:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[08:32:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1535)
[08:32:19 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[08:32:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1458)
[08:32:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1227)
[08:32:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[08:32:19 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[08:32:19 ERROR]: #!#!
[08:32:19 ERROR]: #!#! Version Information:
[08:32:19 ERROR]: #!#!   Skript: 2.6.1
[08:32:19 ERROR]: #!#!     Flavor: skriptlang-github
[08:32:19 ERROR]: #!#!     Date: 22:18:42.554713200
[08:32:19 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[08:32:19 ERROR]: #!#!   Minecraft: 1.18.2
[08:32:19 ERROR]: #!#!   Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
[08:32:19 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[08:32:19 ERROR]: #!#!
[08:32:19 ERROR]: #!#! Server platform: Paper
[08:32:19 ERROR]: #!#!
[08:32:19 ERROR]: #!#! Current node: null
[08:32:19 ERROR]: #!#! Current item: client side armour
[08:32:19 ERROR]: #!#! Current trigger: projectile shoot (simple event) (enderpearl.sk, line 1)
[08:32:19 ERROR]: #!#!
[08:32:19 ERROR]: #!#! Thread: Server thread
[08:32:19 ERROR]: #!#!
[08:32:19 ERROR]: #!#! Language: english
[08:32:19 ERROR]: #!#! Link parse mode: DISABLED
[08:32:19 ERROR]: #!#!
[08:32:19 ERROR]: #!#! End of Error.
[08:32:19 ERROR]: #!#!`

Here's the line
make shooter appear to be wearing air in slot itemslot.head

**Comment by TheLimeGlass** [comment]
Fixed in 1.0.9
