### ISSUE TITLE
client world border send error

### ISSUE THREAD

**Issue by jung27** [TheLimeGlass/Skacket#70]
paper 1.18.2, skript 2.6.1, skacket 1.0.9, protocol 4.8.0

**this is my code**
`command /wb:
    trigger:
        set {_border} to new client border for world "world"
        set {_border}'s client border center to player's location
        set {_border}'s client border radius to 10
        set client border of player to {_border}`

**this is error**
`[20:37:11 ERROR]: #!#!
[20:37:11 ERROR]: #!#! [Skript] Severe Error:
[20:37:11 ERROR]: #!#!
[20:37:11 ERROR]: #!#! Something went horribly wrong with Skript.
[20:37:11 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:37:11 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:37:11 ERROR]: #!#! Here is full list of them:
[20:37:11 ERROR]: #!#! skRayFall v1.9.27 (https://sk.rayfall.net/) SkJade v1.4 (https://www.github.com/Ankoki-Dev/SkJade) SkBee v1.15.1 (https://github.com/ShaneBeee/SkBee) Skacket v1.0.9 SkQuery v4.1.6
[20:37:11 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:37:11 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:37:11 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:37:11 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:37:11 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:37:11 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:37:11 ERROR]: #!#!
[20:37:11 ERROR]: #!#! Stack trace:
[20:37:11 ERROR]: #!#! java.lang.IllegalArgumentException: Could not find packet for type WORLD_BORDER
[20:37:11 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.lambda$getPacketClassFromType$0(PacketRegistry.java:379)
[20:37:11 ERROR]: #!#!     at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[20:37:11 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:379)
[20:37:11 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:95)
[20:37:11 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:130)
[20:37:11 ERROR]: #!#!     at Skacket-1.0.9.jar//me.limeglass.skacket.wrappers.WrapperPlayServerWorldBorder.<init>(WrapperPlayServerWorldBorder.java:11)
[20:37:11 ERROR]: #!#!     at Skacket-1.0.9.jar//me.limeglass.skacket.objects.ClientWorldBorder.send(ClientWorldBorder.java:102)
[20:37:11 ERROR]: #!#!     at Skacket-1.0.9.jar//me.limeglass.skacket.elements.effects.EffSendClientBorder.execute(EffSendClientBorder.java:39)
[20:37:11 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:51)
[20:37:11 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[20:37:11 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[20:37:11 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[20:37:11 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285)
[20:37:11 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:250)
[20:37:11 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255)
[20:37:11 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:258)
[20:37:11 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:175)
[20:37:11 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[20:37:11 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[20:37:11 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:37:11 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631)
[20:37:11 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2381)
[20:37:11 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2200)
[20:37:11 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2181)
[20:37:11 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[20:37:11 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[20:37:11 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[20:37:11 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:37:11 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[20:37:11 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[20:37:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1426)
[20:37:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[20:37:11 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[20:37:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1403)
[20:37:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1396)
[20:37:11 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[20:37:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1374)
[20:37:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1256)
[20:37:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[20:37:11 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[20:37:11 ERROR]: #!#!
[20:37:11 ERROR]: #!#! Version Information:
[20:37:11 ERROR]: #!#!   Skript: 2.6.1 (latest)
[20:37:11 ERROR]: #!#!     Flavor: skriptlang-github
[20:37:11 ERROR]: #!#!     Date: 22:18:42.554713200
[20:37:11 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[20:37:11 ERROR]: #!#!   Minecraft: 1.18.2
[20:37:11 ERROR]: #!#!   Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
[20:37:11 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[20:37:11 ERROR]: #!#!
[20:37:11 ERROR]: #!#! Server platform: Paper
[20:37:11 ERROR]: #!#!
[20:37:11 ERROR]: #!#! Current node: null
[20:37:11 ERROR]: #!#! Current item: client border send
[20:37:11 ERROR]: #!#! Current trigger: command /qwe (simple event) (island.sk, line 37)
[20:37:11 ERROR]: #!#!
[20:37:11 ERROR]: #!#! Thread: Server thread
[20:37:11 ERROR]: #!#!
[20:37:11 ERROR]: #!#! Language: english
[20:37:11 ERROR]: #!#! Link parse mode: DISABLED
[20:37:11 ERROR]: #!#!
[20:37:11 ERROR]: #!#! End of Error.
[20:37:11 ERROR]: #!#!`

**Comment by TheLimeGlass** [comment]
World Borders only work on 1.16.3 and lower. Working on an updated patch.
