### ISSUE TITLE
Open Anvil and Sign GUI error

### ISSUE THREAD

**Issue by Mightinity** [TheLimeGlass/Skacket#75]
[14:48:03 ERROR]: #!#! 
[14:48:03 ERROR]: #!#! [Skript] Severe Error:
[14:48:03 ERROR]: #!#! 
[14:48:03 ERROR]: #!#! Something went horribly wrong with Skript.
[14:48:03 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:48:03 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:48:03 ERROR]: #!#! Here is full list of them:
[14:48:03 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.27 (https://sk.rayfall.net/) Skacket v1.0.5 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/) Reqn v1.2.1 SharpSK v1.6.3 Skent v3.1.0 DiscordSRV v1.25.1 (https://github.com/DiscordSRV/DiscordSRV) skript-reflect v2.2.2-dev (https://github.com/TPGamesNL/skript-reflect) SkriptJSON v1.0.0 DiSky v2.1 (https://disky.itsthesky.info/) skUtilities v0.9.2 (https://tim740.github.io/) skript-yaml v1.4 SkBee v1.9.1 (https://github.com/ShaneBeee/SkBee) SkQuery v4.1.4 
[14:48:03 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:48:03 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:48:03 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:48:03 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:48:03 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:48:03 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[14:48:03 ERROR]: #!#! 
[14:48:03 ERROR]: #!#! Stack trace:
[14:48:03 ERROR]: #!#! java.lang.NoSuchFieldError: hasDelayBefore
[14:48:03 ERROR]: #!#!     at me.limeglass.skacket.sections.Section.loadSection(Section.java:106)
[14:48:03 ERROR]: #!#!     at me.limeglass.skacket.elements.sections.SecOpenSign.initalize(SecOpenSign.java:33)
[14:48:03 ERROR]: #!#!     at me.limeglass.skacket.sections.Section.init(Section.java:59)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:254)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:77)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:254)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.loadCode(Section.java:90)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:254)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.loadCode(Section.java:90)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:254)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.loadCode(Section.java:90)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:254)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[14:48:03 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[14:48:03 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:48:03 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:48:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1400)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[14:48:03 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[14:48:03 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[14:48:03 ERROR]: #!#! 
[14:48:03 ERROR]: #!#! Version Information:
[14:48:03 ERROR]: #!#!   Skript: 2.6.2 (latest)
[14:48:03 ERROR]: #!#!     Flavor: skriptlang-github
[14:48:03 ERROR]: #!#!     Date: 19:12:53.596652600
[14:48:03 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[14:48:03 ERROR]: #!#!   Minecraft: 1.16.5
[14:48:03 ERROR]: #!#!   Java: 16.0.2 (OpenJDK 64-Bit Server VM 16.0.2+7-67)
[14:48:03 ERROR]: #!#!   OS: Linux amd64 4.15.0-175-generic
[14:48:03 ERROR]: #!#! 
[14:48:03 ERROR]: #!#! Server platform: Paper
[14:48:03 ERROR]: #!#! 
[14:48:03 ERROR]: #!#! Current node: null
[14:48:03 ERROR]: #!#! Current item: null
[14:48:03 ERROR]: #!#! 
[14:48:03 ERROR]: #!#! Thread: Server thread
[14:48:03 ERROR]: #!#! 
[14:48:03 ERROR]: #!#! Language: english
[14:48:03 ERROR]: #!#! Link parse mode: DISABLED
[14:48:03 ERROR]: #!#! 
[14:48:03 ERROR]: #!#! End of Error.
[14:48:03 ERROR]: #!#!

**Comment by TheLimeGlass** [comment]
Show your script coding
