### ISSUE TITLE
[1.19.3] Skacket doesn't work

### ISSUE THREAD

**Issue by Deichor** [TheLimeGlass/Skacket#95]
`[16:30:56 ERROR]: [Skacket] Unhandled exception occurred in onPacketSending(PacketEvent) for Skacket
java.lang.IllegalArgumentException: Unrecognized type class net.minecraft.network.syncher.DataWatcher$b
        at com.comphenix.protocol.wrappers.BukkitConverters$8.getSpecific(BukkitConverters.java:639) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$8.getSpecific(BukkitConverters.java:626) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:50) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters.getSpecificList(BukkitConverters.java:321) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters.access$000(BukkitConverters.java:91) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$3.getSpecific(BukkitConverters.java:365) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$3.getSpecific(BukkitConverters.java:362) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:50) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:274) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:224) ~[ProtocolLib.jar:?]
        at com.sitrica.glowing.packets.WrapperPlayServerEntityMetadata.getMetadata(WrapperPlayServerEntityMetadata.java:91) ~[Skacket-1.0.13.jar:?]
        at com.sitrica.glowing.GlowingAPI$2.onPacketSending(GlowingAPI.java:80) ~[Skacket-1.0.13.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:430) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendPairingData(ServerEntity.java:279) ~[?:?]
        at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:262) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:1614) ~[?:?]
        at net.citizensnpcs.nms.v1_19_R2.util.PlayerlistTracker.b(PlayerlistTracker.java:60) ~[Citizens-2.0.30-b2929.jar:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:1527) ~[?:?]
        at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:1257) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1278) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:818) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:649) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:686) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-399]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[16:30:56 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata@7241b329[
    b=10
    c=[b[id=2, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@2aac3de3, value=Optional[literal{Psychic}[style={color=light_purple,!bold,!italic,!underlined,!strikethrough,!obfuscated}]]], b[id=9, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@253c7fe4, value=20.0], b[id=3, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@6c0b2203, value=true], b[id=17, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@44479d1c, value=-1]]`

**Comment by Swemf** [comment]
It works fine for me, it still gives that error though

**Comment by Deichor** [comment]
> 

`
java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:486) ~[?:?]
        at me.limeglass.skacket.elements.sections.SecOpenAnvil.walk(SecOpenAnvil.java:116) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85) ~[?:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:129) ~[?:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299) ~[?:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at io.github.apickledwalrus.skriptgui.elements.sections.SecMakeGUI.lambda$walk$0(SecMakeGUI.java:115) ~[?:?]
        at io.github.apickledwalrus.skriptgui.gui.GUI$1.onClick(GUI.java:44) ~[?:?]
        at io.github.apickledwalrus.skriptgui.gui.events.GUIEvents.onInventoryClick(GUIEvents.java:125) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor319.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-420]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-420]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3165) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-420]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: AnvilGUI does not support server version "1_19_R2" [in thread "Server thread"]
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:34) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:486) ~[?:?]
        at me.limeglass.skacket.elements.sections.SecOpenAnvil.walk(SecOpenAnvil.java:116) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85) ~[?:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:129) ~[?:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299) ~[?:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at io.github.apickledwalrus.skriptgui.elements.sections.SecMakeGUI.lambda$walk$0(SecMakeGUI.java:115) ~[?:?]
        at io.github.apickledwalrus.skriptgui.gui.GUI$1.onClick(GUI.java:44) ~[?:?]
        at io.github.apickledwalrus.skriptgui.gui.events.GUIEvents.onInventoryClick(GUIEvents.java:125) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor319.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-420]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-420]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3165) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-420]
        ... 2 more
`

**Comment by TheLimeGlass** [comment]
Fixed in 1.1.0
