### ISSUE TITLE
what bug is this?

### ISSUE THREAD

**Issue by cyclsunmark** [TheLimeGlass/Skacket#99]
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at me.limeglass.skacket.wrappers.WrapperPlayServerNamedSoundEffect.getSoundEffect(WrapperPlayServerNamedSoundEffect.java:23) ~[Skacket-1.0.13.jar:?]
        at me.limeglass.skacket.listeners.PacketListeners$1.onPacketSending(PacketListeners.java:51) ~[Skacket-1.0.13.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2234) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.playSound(CraftPlayer.java:812) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at ch.njol.skript.effects.EffPlaySound.playSound(EffPlaySound.java:170) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.effects.EffPlaySound.execute(EffPlaySound.java:144) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[Skript-2.6.4.jar:?]
        at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71) ~[Skript-2.6.4.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1916]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at fr.anarchick.skriptpacket.packets.SPPacketAdapter.onPacketReceiving(SPPacketAdapter.java:40) ~[skript-packet-main-2.1.1.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:625) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.lambda$syncStart$3(AsyncListenerHandler.java:425) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1916]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[11:28:05 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutNamedSoundEffect@d4ee3aa[
    b=Direct{net.minecraft.sounds.SoundEffect@8f05d3f}
    c=MASTER
    d=1058
    e=0
    f=154
    g=3.0
    h=50.0
    i=-3036728625652419153
  ]

>

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/TheLimeGlass/Skacket/issues/93
